version: '2.0'
services:
  loadbalancer:
    build: iosr-loadbalancer
    ports:
      - "8765:8765"
    restart: always
    depends_on:
      - logstash

  eureka:
    build: iosr-server
    restart: always
    depends_on:
      - logstash

  project:
    build: iosr-project
    restart: always
    depends_on:
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  manipulator:
    build: iosr-manipulation-service
    restart: always
    depends_on:
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    ports:
      - "9200:9200"
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    ports:
      - "25826:25826"
    volumes:
      - $PWD/elk-config:/elk-config
    command: logstash -f /elk-config/logstash.config
    depends_on:
      - elasticsearch

